### ISSUE TITLE
symbol lookup error: undefined symbol: mkl_serv_getenv

### ISSUE THREAD

**Issue by zsoerenm** [JuliaMath/VML.jl#12] opened 2017-03-01 13:28 UTC
I have installed intel-mkl from arch aur repository: https://aur.archlinux.org/packages/intel-mkl/

After that I have linked the following:
`sudo ln -s /opt/intel/lib/* /usr/local/lib/`

But I still get an error:
```
julia: symbol lookup error: /opt/intel/mkl/lib/intel64/libmkl_vml_avx.so: undefined symbol: mkl_serv_getenv
```
Googling does not help here unfortunately.

**Comment by Djoop** [comment] 2018-09-24 14:05
The issue is old, but I ran into the same error recently, so I'm answering.
I had this error when trying to use VML with a julia binary which had not been compiled with MKL. I don't understand how these libraries work, but I was thinking that maybe VML was an independent library that could be used without julia being compiled against MKL (although you need of course to download MKL to get the VML library). If being compiled against MKL is a requirement, maybe it should be written explicitly on the README, as it might not be obvious to all users? If this is not a requirement, then I have no clue on how to solve the problem.
That being said, maybe you encounter the same error for a different reason.

**Comment by WilliamTambellini** [comment] 2019-11-22 22:02
Perhaps the same error that is happening with python and java : mkl_core is dynamic loading the mkl libs which does nt always work well. Many are just LD_PRELOAD the mkl libs.

**Comment by aminya** [comment] 2019-11-26 02:58
Could you test with the latest release?

**Comment by Crown421** [comment] 2019-11-27 22:42
I had this error when I started working on it, the solution was adding some flags to the `Libdl.dlopen` command. 
I am successfully using https://aur.archlinux.org/packages/intel-mkl-slim/ on Manjaro, so I am closing this issue. Please comment if it is not working for you, then I will reopen and investigate.

**Closed by Crown421** 2019-11-27 22:42 UTC
